[#115] E#11-S#5 회원가입 뷰 구현 (확정 전)
TeamSodam/sodam-client pull request #120
Opened 2022-03-05 08:17 UTC by huiseon37

## ✨ 구현 기능 명세
회원가입 뷰 구현했습니다. 아직 디자인 확정 전이라 나오는대로 수정할 예정입니다~ 기능 구현을 위해서 껍데기만 대충 만들어 놨어요! 색상도 안나왔길래 제맘대로 때려박았습니다~ 수정예정~

## 🎁 PR Point
반복되는 컴포넌트를 어케 해야할지몰라서 일단 짜긴했는데 조잡한 느낌이 들어요..

## 🕰 소요시간
8h..?

## 😭 어려웠던 점
그냥... 마니어려워따~...

2022-03-05 09:56 UTC, KimKwon requested changes
고생하셔써요
아마 기능부여하다보면 계속 수정될것같네유

2022-03-05 09:56 UTC, KimKwon commented on src/components/Auth/SignupOption.tsx
> +  type: string;
```suggestion
  type: 'nickname' | 'emailConfirm' | 'password';
```

정확한 타입을 제공할 수 있을 것 같네요~

2022-03-05 09:56 UTC, KimKwon commented on src/components/common/PersonalInfoInput.tsx
> +  }, [inputValue.value]);
결국 input의 onchange 핸들러가 `handleOnChange` 함수가 되는거니까 
useInput 커스텀 훅에 handleOnChange를 넘겨서 사용하는 방식도 괜찮을 것 같아요

2022-03-08 07:46 UTC, huiseon37 commented on src/components/common/PersonalInfoInput.tsx
> +  }, [inputValue.value]);
수정해씀다 확인해주세욤

2022-03-13 08:27 UTC, KimKwon approved these changes
변경사항 확인했습니다 고생해써요

2022-03-24 06:04 UTC, KimKwon requested changes
회원가입 부분 GUI 확정 나왔으니 이 PR 마무리하고 
새로운 브랜치에서 작업하면 될 것 같아요 고생해써요 😀

2022-03-24 06:04 UTC, KimKwon commented on src/components/Auth/SignupOption.tsx
> +  };
```suggestion
  const getSignOption = (type: string) => {
    switch (type) {
      case 'nickname':
        return <StyledBtn tabIndex={-1}>중복확인</StyledBtn>;
      case 'emailConfirm':
        return <StyledBtn tabIndex={-1}>확인</StyledBtn>;
      case 'password':
        return <StyledNotice>‘영문 소문자 + 숫자’ 포함하여 8글자 이상 15자 미만</StyledNotice>;
      default:
        return null;
    }
  };
```
웹에서 여러개의 폼을 입력할 때 사용자들은 tab을 이용해 다음 입력 창으로 이동하는데 
이름에서 닉네임으로 tab을 사용해 넘어갈 때 중복확인에 걸리게 되어서 불편한 감이 있더라구요.

> MDN: 음의 정숫값(보통 tabindex="-1")은 연속 키보드 탐색으로 접근할 수는 없으나 JavaScript나 시각적(마우스 클릭)으로는 포커스 가능함을 뜻합니다. 보통 JavaScript를 사용한 위젯의 접근성 확보를 위해 사용합니다.

한번 직접 적용해보시고 차이를 확인해보면 좋을 것 같아요!

2022-03-24 07:10 UTC, merged